---
name: Release Please

"on":
  push:
    # 将main改为master
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .release-please.yml
          github-api-url: https://api.github.com
          github-graphql-url: https://api.github.com/graphql
          changelog-host: https://github.com
